package udemy.fausto.com.temp_recyclerc

class DataService {
    val persons : List<Person> = listOf(
        Person("Fausto", "6", "perro1"),
        Person("Nacho", "4", "perro2"),
        Person("Félix", "8", "perro3"),
        Person("Nacho", "10", "perro4"),
        Person("Aurelia", "10", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "20", "perro7"),
        Person("Juani", "14", "perro8"),
        Person("Paco", "12", "perro9"),
        Person("David", "10", "perro4"),
        Person("Roberto", "12", "perro5"),
        Person("Fausto", "8", "perro1"),
        Person("Nacho", "14", "perro2"),
        Person("Félix", "12", "perro3"),
        Person("Nacho", "18", "perro4"),
        Person("Aurelia", "10", "perro5"),
        Person("Juan", "9", "perro6"),
        Person("Carlos", "12", "perro7"),
        Person("Juani", "11", "perro8"),
        Person("Paco", "10", "perro9"),
        Person("David", "9", "perro4"),
        Person("Roberto", "16", "perro5"),
        Person("Fausto", "12", "perro1"),
        Person("Nacho", "13", "perro2"),
        Person("Félix", "9", "perro3"),
        Person("Nacho", "10", "perro4"),
        Person("Aurelia", "11", "perro5"),
        Person("Juan", "12", "perro6"),
        Person("Carlos", "20", "perro7"),
        Person("Juani", "9", "perro8"),
        Person("Paco", "6", "perro9"),
        Person("David", "12", "perro4"),
        Person("Roberto", "10", "perro5"),
        Person("Fausto", "11", "perro1"),
        Person("Nacho", "18", "perro2"),
        Person("Félix", "14", "perro3"),
        Person("Nacho", "12", "perro4"),
        Person("Aurelia", "13", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "20", "perro7"),
        Person("Juani", "8", "perro8"),
        Person("Paco", "6", "perro9"),
        Person("David", "9", "perro4"),
        Person("Roberto", "12", "perro5"),
        Person("Fausto", "6", "perro1"),
        Person("Nacho", "12", "perro2"),
        Person("Félix", "9", "perro3"),
        Person("Nacho", "10", "perro4"),
        Person("Aurelia", "11", "perro5"),
        Person("Juan", "12", "perro6"),
        Person("Carlos", "7", "perro7"),
        Person("Juani", "14", "perro8"),
        Person("Paco", "13", "perro9"),
        Person("David", "16", "perro4"),
        Person("Roberto", "12", "perro5"),
        Person("Fausto", "11", "perro1"),
        Person("Nacho", "12", "perro2"),
        Person("Félix", "13", "perro3"),
        Person("Nacho", "14", "perro4"),
        Person("Aurelia", "15", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "9", "perro7"),
        Person("Juani", "10", "perro8"),
        Person("Paco", "11", "perro9"),
        Person("David", "12", "perro4"),
        Person("Roberto", "13", "perro5"),
        Person("Carlos", "7", "perro7"),
        Person("Juani", "8", "perro8"),
        Person("Paco", "14", "perro9"),
        Person("David", "16", "perro4"),
        Person("Roberto", "11", "perro5"),
        Person("Fausto", "6", "perro1"),
        Person("Nacho", "7", "perro2"),
        Person("Félix", "8", "perro3"),
        Person("Nacho", "5", "perro4"),
        Person("Aurelia", "6", "perro5"),
        Person("Juan", "6", "perro6"),
        Person("Carlos", "7", "perro7"),
        Person("Juani", "8", "perro8"),
        Person("Paco", "6", "perro9"),
        Person("David", "6", "perro4"),
        Person("Roberto", "14", "perro5")


    )


}

